version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: blitz-trades-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
    networks:
      - blitz-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blitz-trades-backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://root:secretpassword@mongodb:27017/blitz-trades?authSource=admin
      - JWT_SECRET=your-secret-key-change-in-production
      - JWT_EXPIRES_IN=24h
    networks:
      - blitz-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blitz-trades-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - blitz-network

networks:
  blitz-network:
    driver: bridge

volumes:
  mongodb_data: